program xpc;

{$mode objfpc}{$H+}

uses
  SysUtils;

const
  XPascalVersion = '0.0.0-bootstrap';
  RequiredFpcVersion = '3.3.1';

function TargetOs: string;
begin
  {$IFDEF WINDOWS}
  Result := 'windows';
  {$ELSEIF DEFINED(DARWIN)}
  Result := 'macos';
  {$ELSEIF DEFINED(LINUX)}
  Result := 'linux';
  {$ELSE}
  Result := 'unknown';
  {$ENDIF}
end;

function TargetCpu: string;
begin
  {$IFDEF CPUX86_64}
  Result := 'x86_64';
  {$ELSEIF DEFINED(CPUAARCH64)}
  Result := 'aarch64';
  {$ELSEIF DEFINED(CPUI386)}
  Result := 'i386';
  {$ELSE}
  Result := 'unknown';
  {$ENDIF}
end;

function IsProjectNameValid(const Name: string): Boolean;
var
  I: Integer;
  C: Char;
begin
  if Name = '' then
    Exit(False);

  C := Name[1];
  if not (C in ['A'..'Z', 'a'..'z', '_']) then
    Exit(False);

  for I := 1 to Length(Name) do
  begin
    C := Name[I];
    if not (C in ['A'..'Z', 'a'..'z', '0'..'9', '_']) then
      Exit(False);
  end;

  Result := True;
end;

procedure WriteTextFile(const FileName, Content: string);
var
  F: TextFile;
begin
  AssignFile(F, FileName);
  Rewrite(F);
  try
    Write(F, Content);
  finally
    CloseFile(F);
  end;
end;

procedure PrintVersion;
var
  FpcVersion: string;
begin
  WriteLn('XPascal/XRTL ', XPascalVersion);
  WriteLn('target: ', TargetOs, '-', TargetCpu);
  FpcVersion := GetEnvironmentVariable('FPC_VERSION');
  if FpcVersion <> '' then
    WriteLn('fpc: ', FpcVersion)
  else
    WriteLn('fpc: not verified');
end;

function Doctor: Integer;
var
  FpcVersion: string;
begin
  WriteLn('xpc doctor');
  WriteLn('target: ', TargetOs, '-', TargetCpu);

  FpcVersion := GetEnvironmentVariable('FPC_VERSION');
  if FpcVersion = '' then
  begin
    WriteLn('fail: FreePascal version was not verified');
    WriteLn('hint: run xpc through tools/run-xpc after tools/check-toolchain');
    Exit(1);
  end;

  WriteLn('fpc: ', FpcVersion);
  if FpcVersion <> RequiredFpcVersion then
  begin
    WriteLn('fail: expected fpc ', RequiredFpcVersion);
    Exit(1);
  end;

  WriteLn('ok: FreePascal toolchain is pinned to ', RequiredFpcVersion);
  Result := 0;
end;

function Build: Integer;
var
  FpcVersion: string;
begin
  WriteLn('xpc build');
  WriteLn('target: ', TargetOs, '-', TargetCpu);

  FpcVersion := GetEnvironmentVariable('FPC_VERSION');
  if FpcVersion = '' then
  begin
    WriteLn('fail: FreePascal version was not verified');
    WriteLn('hint: run xpc build through tools/run-xpc after tools/check-toolchain');
    Exit(1);
  end;

  WriteLn('fpc: ', FpcVersion);
  if FpcVersion <> RequiredFpcVersion then
  begin
    WriteLn('fail: expected fpc ', RequiredFpcVersion);
    Exit(1);
  end;

  WriteLn('fail: direct in-process build is not available in bootstrap CLI v0');
  WriteLn('hint: use tools/run-xpc build so the platform launcher can invoke the correct build script');
  Result := 1;
end;

function NewProject: Integer;
var
  ProjectName: string;
  ProjectDir: string;
  SrcDir: string;
begin
  if ParamCount <> 2 then
  begin
    WriteLn('fail: expected project name');
    WriteLn('usage: xpc new <project_name>');
    Exit(64);
  end;

  ProjectName := ParamStr(2);
  if not IsProjectNameValid(ProjectName) then
  begin
    WriteLn('fail: invalid project name: ', ProjectName);
    WriteLn('hint: use letters, numbers, and underscores; start with a letter or underscore');
    Exit(64);
  end;

  ProjectDir := ExpandFileName(ProjectName);
  if DirectoryExists(ProjectDir) or FileExists(ProjectDir) then
  begin
    WriteLn('fail: target already exists: ', ProjectName);
    Exit(1);
  end;

  SrcDir := IncludeTrailingPathDelimiter(ProjectDir) + 'src';
  if not ForceDirectories(SrcDir) then
  begin
    WriteLn('fail: could not create project directory: ', ProjectName);
    Exit(1);
  end;

  WriteTextFile(IncludeTrailingPathDelimiter(ProjectDir) + 'xproject.toml',
    'name = "' + ProjectName + '"' + LineEnding +
    'version = "0.1.0"' + LineEnding +
    'main = "src/main.pas"' + LineEnding);

  WriteTextFile(IncludeTrailingPathDelimiter(SrcDir) + 'main.pas',
    'program ' + ProjectName + ';' + LineEnding + LineEnding +
    '{$mode objfpc}{$H+}' + LineEnding + LineEnding +
    'begin' + LineEnding +
    '  WriteLn(''hello from ' + ProjectName + ''');' + LineEnding +
    'end.' + LineEnding);

  WriteTextFile(IncludeTrailingPathDelimiter(ProjectDir) + 'README.md',
    '# ' + ProjectName + LineEnding + LineEnding +
    'Generated by `xpc new`.' + LineEnding + LineEnding +
    'Build from the XPascal/XRTL repository root with:' + LineEnding + LineEnding +
    '```powershell' + LineEnding +
    './tools/run-xpc.ps1 build ' + ProjectName + LineEnding +
    '```' + LineEnding + LineEnding +
    '```bash' + LineEnding +
    'bash ./tools/run-xpc.sh build ' + ProjectName + LineEnding +
    '```' + LineEnding);

  WriteLn('created: ', ProjectName);
  WriteLn('next: tools/run-xpc build ', ProjectName);
  Result := 0;
end;

procedure PrintHelp;
begin
  WriteLn('xpc - XPascal bootstrap CLI');
  WriteLn;
  WriteLn('Usage:');
  WriteLn('  xpc version');
  WriteLn('  xpc doctor');
  WriteLn('  xpc build');
  WriteLn('  xpc new <project_name>');
  WriteLn('  xpc help');
end;

var
  Command: string;
begin
  if ParamCount = 0 then
  begin
    PrintHelp;
    Halt(0);
  end;

  Command := LowerCase(ParamStr(1));
  case Command of
    'version':
      begin
        PrintVersion;
        Halt(0);
      end;
    'doctor':
      Halt(Doctor);
    'build':
      Halt(Build);
    'new':
      Halt(NewProject);
    'help', '--help', '-h':
      begin
        PrintHelp;
        Halt(0);
      end;
    else
      begin
        WriteLn('unknown command: ', ParamStr(1));
        PrintHelp;
        Halt(64);
      end;
  end;
end.
